added support for https odoo instance
pridiktiv/odoo-connect pull request #6
Opened 2017-11-03 12:31 UTC by manjeet-bhatkar

2017-12-28 18:50 UTC, SamVerschueren requested changes
Can you also rebase against master? Did a minor change.

2017-12-28 18:50 UTC, SamVerschueren commented on lib/odoo.js
> +module.exports = Odoo;
Add final newline

2017-12-28 18:50 UTC, SamVerschueren commented on lib/request.js
> +};
Add final newline

2018-01-02 11:10 UTC, manjeet-bhatkar commented
Hi @SamVerschueren , I have made changes and rebase against master. Please check following PR
https://github.com/manjeet-bhatkar/odoo-connect/pull/2

2018-01-23 16:21 UTC, ivantodorovich commented
Same problem here. What does it take for this to get merged?

2018-01-23 19:49 UTC, SamVerschueren approved these changes

2018-01-23 20:04 UTC, merged

2018-01-24 05:05 UTC, SamVerschueren commented
Thanks for the PR! Will release a new version soon.